trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: 'multiple-env/env/dev'

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'tfstatefile'

    backendAzureRmResourceGroupName: 'POC'
    backendAzureRmStorageAccountName: 'tfstatepoc2026'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev/terraform.tfstate'
    workingDirectory: '$(workingDirectory)'

- task: TerraformTaskV4@4
  displayName: Terraform Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(workingDirectory)'

- task: TerraformTaskV4@4
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'tfstatefile'
    workingDirectory: '$(workingDirectory)'

  env:
    TF_VAR_db_password: $(var.db_password)
